USE TopDrivers;

INSERT IGNORE INTO `Resource`
(Name, Description, Url, Path, IsEnabled, IsActive, Created, CreatedBy)
VALUES
('Conducción','Foto 1','https://escuelademanejotopdrivers.com:8080/Galeria1.webp', '/var/www/Galeria/Galeria1.webp', true, true, '2021-10-05 03:52:13','admin'),
('Conducción','Foto 2','https://escuelademanejotopdrivers.com:8080/Galeria2.webp', '/var/www/Galeria/Galeria2.webp', true, true, '2021-10-05 03:52:13','admin'),
('Conducción','Foto 3','https://escuelademanejotopdrivers.com:8080/Galeria3.webp', '/var/www/Galeria/Galeria3.webp', true, true, '2021-10-05 03:52:13','admin'),
('Conducción','Foto 4','https://escuelademanejotopdrivers.com:8080/Galeria4.webp', '/var/www/Galeria/Galeria4.webp', true, true, '2021-10-05 03:52:13','admin'),
('Conducción','Foto 5','https://escuelademanejotopdrivers.com:8080/Galeria5.webp', '/var/www/Galeria/Galeria5.webp', true, true, '2021-10-05 03:52:13','admin'),
('Conducción','Foto 6','https://escuelademanejotopdrivers.com:8080/Galeria6.webp', '/var/www/Galeria/Galeria6.webp', true, true, '2021-10-05 03:52:13','admin'),
('Conducción','Foto 7','https://escuelademanejotopdrivers.com:8080/Galeria7.webp', '/var/www/Galeria/Galeria7.webp', true, true, '2021-10-05 03:52:13','admin'),
('Conducción','Foto 8','https://escuelademanejotopdrivers.com:8080/Galeria8.webp', '/var/www/Galeria/Galeria8.webp', true, true, '2021-10-05 03:52:13','admin'),
('Conducción','Foto 9','https://escuelademanejotopdrivers.com:8080/Galeria9.webp', '/var/www/Galeria/Galeria9.webp', true, true, '2021-10-05 03:52:13','admin'),
('Conducción','Foto 10','https://escuelademanejotopdrivers.com:8080/Galeria10.webp', '/var/www/Galeria/Galeria10.webp', true, true, '2021-10-05 03:52:13','admin'),
('Conducción','Foto 11','https://escuelademanejotopdrivers.com:8080/Galeria11.webp', '/var/www/Galeria/Galeria11.webp', true, true, '2021-10-05 03:52:13','admin'),
('Conducción','Foto 12','https://escuelademanejotopdrivers.com:8080/Galeria12.webp', '/var/www/Galeria/Galeria12.webp', true, true, '2021-10-05 03:52:13','admin'),
('Conducción','Foto 13','https://escuelademanejotopdrivers.com:8080/Galeria13.webp', '/var/www/Galeria/Galeria13.webp', true, true, '2021-10-05 03:52:13','admin'),
('Conducción','Foto 14','https://escuelademanejotopdrivers.com:8080/Galeria14.webp', '/var/www/Galeria/Galeria14.webp', true, true, '2021-10-05 03:52:13','admin'),
('Conducción','Foto 15','https://escuelademanejotopdrivers.com:8080/Galeria15.webp', '/var/www/Galeria/Galeria15.webp', true, true, '2021-10-05 03:52:13','admin'),
('Conducción','Foto 16','https://escuelademanejotopdrivers.com:8080/Galeria16.webp', '/var/www/Galeria/Galeria16.webp', true, true, '2021-10-05 03:52:13','admin'),
('Conducción','Foto 17','https://escuelademanejotopdrivers.com:8080/Galeria17.webp', '/var/www/Galeria/Galeria17.webp', true, true, '2021-10-05 03:52:13','admin'),
('Conducción','Foto 18','https://escuelademanejotopdrivers.com:8080/Galeria18.webp', '/var/www/Galeria/Galeria18.webp', true, true, '2021-10-05 03:52:13','admin'),
('Conducción','Foto 19','https://escuelademanejotopdrivers.com:8080/Galeria19.webp', '/var/www/Galeria/Galeria19.webp', true, true, '2021-10-05 03:52:13','admin'),
('Conducción','Foto 20','https://escuelademanejotopdrivers.com:8080/Galeria20.webp', '/var/www/Galeria/Galeria20.webp', true, true, '2021-10-05 03:52:13','admin'),
('Conducción','Foto 21','https://escuelademanejotopdrivers.com:8080/Galeria21.webp', '/var/www/Galeria/Galeria21.webp', true, true, '2021-10-05 03:52:13','admin'),
('Conducción','Foto 22','https://escuelademanejotopdrivers.com:8080/Galeria22.webp', '/var/www/Galeria/Galeria22.webp', true, true, '2021-10-05 03:52:13','admin'),
('Conducción','Foto 23','https://escuelademanejotopdrivers.com:8080/Galeria23.webp', '/var/www/Galeria/Galeria23.webp', true, true, '2021-10-05 03:52:13','admin'),
('Conducción','Foto 24','https://escuelademanejotopdrivers.com:8080/Galeria24.webp', '/var/www/Galeria/Galeria24.webp', true, true, '2021-10-05 03:52:13','admin'),
('Conducción','Foto 25','https://escuelademanejotopdrivers.com:8080/Galeria25.webp', '/var/www/Galeria/Galeria25.webp', true, true, '2021-10-05 03:52:13','admin'),
('Conducción','Foto 26','https://escuelademanejotopdrivers.com:8080/Galeria26.webp', '/var/www/Galeria/Galeria26.webp', true, true, '2021-10-05 03:52:13','admin'),
('Conducción','Foto 27','https://escuelademanejotopdrivers.com:8080/Galeria27.webp', '/var/www/Galeria/Galeria27.webp', true, true, '2021-10-05 03:52:13','admin')

